/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:563a6d27-1fbe-46bb-b5ad-b3d307e579be",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xWWyW39Eh",
    "aws_user_pools_web_client_id": "7grsdhdf11tvhh14ja1l49o5jd",
    "oauth": {}
};


export default awsmobile;
